title: DevClave
author: eric_njuki
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Spells and potions
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ericnjuki
github_username:  ericnjuki

# Build settings
markdown: kramdown
# theme: minima
# theme: oldbook
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
